name: relive
description: A memory app built with Flutter and Firebase
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.2
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_storage: ^13.0.0
  cloud_firestore: ^6.0.0
  video_player: ^2.7.2
  chewie: ^1.7.5
  lottie: ^3.3.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  image_picker: ^1.1.2
  http: ^1.2.0
  video_compress: ^3.1.2
  flutter_animate: ^4.5.1
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.4
  intl: ^0.19.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/upload.json
    - assets/animals/

